<?php if ( !defined("ABSPATH") ) die("-1");
/* GENERATED BY "wp-query-factory" on: Wed, 22 Aug 12 16:19:09 +0000 */ ?>
<div class="post-178 wp-query-factory-tpl type-wp-query-factory-tpl status-publish hentry">
<h1><strong><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></strong></h1>
<p><?php the_excerpt(); ?></p></div>